<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Lang strings for aipurpose_questiongeneration - EN.
 *
 * @package    aipurpose_questiongeneration
 * @copyright  ISB Bayern, 2024
 * @author     Dr. Peter Mayer
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'Question generation';
$string['privacy:metadata'] = 'The local ai_manager purpose subplugin "Question generation" does not store any personal data.';
$string['purposedescription'] = 'The purpose "Question generation" is being used by tools that are using an external AI system to generate questions in a format which then can be imported to question banks. This purpose therefore does some additional formatting and sanitizing of the text generated by the external AI system.';
$string['requestcount'] = 'question generation requests';
$string['requestcount_shortened'] = 'question generation';
